### ISSUE TITLE
Selection of pods to be terminated by using multiple labels is not working for me

### ISSUE THREAD

**Issue by ljanatka** [linki/chaoskube#111]
Hi Martin,

I am struggling with multiple labels. I need to select pods for termination using labels (one key with multiple values). If there is only one value, everything works fine. When there are multiple values, the chaoskube runs (in dry mode), there is no error output, but there is also no log about killing the pods. I tried following syntax of "labels" line of yaml file:
- --labels=app=xxx, yyy
- --labels=app=xxx,yyy
- --labels=app=xxx,app=yyy

No luck so far :-(

What is the correct syntax of "labels"? We want to create the "pool" of pods of multiple applications to be killed.

What would be the syntax if I ever need to select pods by multiple keys with multiple values?

Thank You,

Ladislav

**Comment by linki** [comment]
Hi @ljanatka,

the label selector logic is the same as in Kubernetes. That means if you provide multiple label conditions *all* of them must match.

In general, whatever [Kubernetes label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) can do you can do with `chaoskube`.

In order to achieve what you describe you can use the `in` operator:
```console
# includes everything where the `app` label is either `xxx` or `yyy`
$ chaoskube --labels='app in (xxx,yyy)'
```

Another approach is to label or annotate the pods (via Deployment) that should be terminated (or should be excluded from termination) via a separate label/annotation, such as `chaos=true` and then select on this one:
```console
# excludes everything without the `chaos` label
$ chaoskube --labels=chaos=true
```

**Comment by ljanatka** [comment]
Hi @linki,

thanks, that works like a charm!

Have a great day!
