### ISSUE TITLE
Cannot set multiple days in excluded Weekdays

### ISSUE THREAD

**Issue by nipuns11** [linki/chaoskube#136]
$ helm install stable/chaoskube --set dryRun=false --set namespaces=test --set interval=10m --set timezone=America/New_York --set excludedWeekdays="Mon,Wed,Thu,Fri" --set excludedTimesOfDay="08:00-18:00"

**Error: failed parsing --set data: key "Wed" has no value (cannot end with ,)**

Cannot set multiple days in excluded Weekdays

**Comment by linki** [comment]
@nipuns11 Yeah, that's a bit annoying. The reason is that `--set` can take multiple key/value pairs at once and in order to separate them it uses the comma. [See that example for instance](https://github.com/helm/helm/blob/v2.14.3/docs/using_helm.md#the-format-and-limitations-of---set):
> Multiple values are separated by , characters. So --set a=b,c=d becomes:
>
> a: b
> c: d

That makes the comma a reserved character within `--set` values so that you need to escape it.

The following will solve your issue (note the added `\` before the `,` in `excludedWeekdays`):
```console
helm install stable/chaoskube --set dryRun=false --set namespaces=test --set interval=10m --set excludedWeekdays="Mon\,Wed\,Thu\,Fri" --set excludedTimesOfDay="08:00-18:00"
```

**Comment by nipuns11** [comment]
Thanks :-)
