### ISSUE TITLE
Add a logo

### ISSUE THREAD

**Issue by linki** [linki/chaoskube#27]
Now that `chaoskube` is listed on [https://kubeapps.com](https://kubeapps.com/charts/stable/chaoskube) we should get a pretty logo :)

**Comment by dankohn** [comment]
Please create a logo and I will add you to https://landscape.cncf.io/grouping=landscape&landscape=chaos-engineering

**Comment by linki** [comment]
@dankohn I'll try 😄

**Comment by linki** [comment]
@dankohn chaoskube has a logo now: https://github.com/linki/chaoskube/blob/master/chaoskube.png

**Comment by dankohn** [comment]
That's great, but we need an SVG, AI, or EPS. Could you please upload the original of the logo to the repo or zip it and attach here.

**Comment by dankohn** [comment]
That EPS relies on the font `Graebenbach-BlackItalic` which I don't have, so I can't complete the conversion. When CNCF's graphic designer comes back on Tuesday, she'll convert it to an SVG that doesn't need a font and I'll upload.

**Comment by linki** [comment]
Thank you.

**Comment by dankohn** [comment]
And here you go:
https://landscape.cncf.io/category=chaos-engineering&grouping=category&selected=chaoskube

I presumed that it should go in a new chaoskube organization because the
trademark is not owned by Zalando.

I would also encourage you to create a Twitter account for chaoskube that
you post to at least once a month. You can then open a PR with the handle
or just add the info here and I'll update.
--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by linki** [comment]
Thanks a lot!

**Comment by dankohn** [comment]
Now featuring your Twitter: https://landscape.cncf.io/category=chaos-engineering&grouping=category&selected=chaoskube

**Comment by linki** [comment]
Thanks again! :blush:
