### ISSUE TITLE
deployment limits

### ISSUE THREAD

**Issue by kfox1111** [linki/chaoskube#6]
So, I'd really like to use chaoskube to force our deployment objects to have to exercise its connection tracking/safe shutdown code. Some assurances too many pods don't get killed would be good though. Would it be possible to add support for looking at the .spec.strategy.rollingUpdate.maxUnavailable field and the .spec.replica's field to ensure not too many are out at a time?

**Comment by linki** [comment]
That sounds like a reasonable idea. However, as you don't get these guarantees in production I wouldn't tackle it next.

**Comment by linki** [comment]
Instead of manually finding out whether we can kill a particular pod under the above circumstances, we could also enable `chaoskube` to respect any definded [Pod Disruption Budgets](https://kubernetes.io/docs/admin/disruptions/). Basically a "soft" mode.

**Comment by kfox1111** [comment]
Yeah, the use case for me though is existing software. total chaos is great for ensuring clients will work when servers drop out. Lets you build much more reliable clients/servers. All software should be built that way. But as a writer of k8s objects/orchestration for existing software, there's the use case of, ensuring at least the orchestration code is solid by forcing deletes frequently, but not killing connections in a way that the servers/clients never were designed for. This is more the use case I have at the moment.

Pod Disruption Budget support sounds like a great idea. :)

**Comment by kfox1111** [comment]
Sorry. wrong button.

**Comment by linki** [comment]
I looked into `PodDisruptionBudget`s yesterday and they are pretty much want you want.

Kubernetes defines voluntary evictions (e.g. due to draining, auto-downscaling, etc.) and involuntary pod evictions (node failures etc.).

With those budgets you define a label selector and a minimun number of pods that should exists matching this selector. If not you cannot evict the pod. you can still delete it. `kubectl drain` uses evict under the hood in order to honor the disruption budgets. You can still fall under your minimum when an involuntary eviction happens while you are at your minimum value from your disruption budget.

I tested it yesterday with chaoskube and it works as expected. Unfortunately, the golang fake client that I use for writing tests doesn't quite show the same behaviour. It's usually very accurate.

**Comment by kfox1111** [comment]
very cool. thanks for looking into this and letting me know what you found. :)

**Comment by linki** [comment]
@kfox1111 I'm re-labelling this as "respect pod disruption budgets" as it seems to be a good approach to achieve what we want in a general way. The outcode should be that `chaoskube` can be run with a mode respecting the budgets and without for true chaos.

new issue: https://github.com/linki/chaoskube/issues/13

@kfox1111 feel free to re-open if you think this is wrong.

**Comment by kfox1111** [comment]
Sounds good. Thanks. :)
