### ISSUE TITLE
New chart compatible only with k8s > 1.9.0

### ISSUE THREAD

**Issue by shaikatz** [linki/chaoskube#99]
Hi,

Since last update to the chart (version 0.8.1) it's now support only K8S > 1.9.0 (apps/v1 api) which is a blocker for us.
Is this a change is a most or you can reconsider it?

I've successfully ran 0.10.0 image on my k8s 1.8 cluster without the helm chart.

**Comment by linki** [comment]
@shaikatz That's unfortunate 😞

Could you try to use the old chart version and pass a custom `imageTag` to make it work? E.g.

`helm install stable/chaoskube --version 0.8.0 --set imageTag=v0.10.0` 

I think reverting it isn't a good idea. We could maybe make it configurable in the chart's deployment template file. If kubernetes version >1.10 use `apps/v1` otherwise `extensions/v1beta1`, something like that. This isn't a problem specific to chaoskube so I would rather check the other charts to see how they solve it.

**Comment by shaikatz** [comment]
Looks like major charts keep the oldest api they can for backward compatbility:
https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/controller-deployment.yaml
https://github.com/helm/charts/blob/master/stable/artifactory/templates/nginx-deployment.yaml
https://github.com/helm/charts/blob/master/stable/mysql/templates/deployment.yaml
https://github.com/helm/charts/blob/master/incubator/elasticsearch/templates/client-deployment.yaml

**Comment by linki** [comment]
right, but many are also hard-coded to `apps/v1`.

I think we can to the same thing as is done here:
https://github.com/helm/charts/blob/9b98e81d525c62ca7178d4e0229f29a2e067c4c0/stable/traefik/templates/deployment.yaml#L1-L5

I'll open a PR when I've got a little time. But feel free to do it yourself if you want.

**Comment by shaikatz** [comment]
Sounds like a good option.
Opened a PR for that: https://github.com/helm/charts/pull/7195

Thanks!
